sudo: false

language: c

addons:
  apt:
    packages:
    - libgmp-dev
    - libgdal1-dev
    - gdal-bin
    - valgrind

env:
  - ARGS="--resolver lts-2"
  - ARGS="--resolver lts-3"
  - ARGS="--resolver nightly"

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'
- stack $ARGS --no-terminal --install-ghc setup
- stack $ARGS exec c2hs -- --version
- gdalinfo --version

script:
- stack $ARGS --no-terminal test --haddock
- find .stack-work -type f -name spec -exec valgrind --leak-check=full {} ';'

cache:
  directories:
  - $HOME/.stack
