sudo: false

language: c

addons:
  apt:
    packages:
    - libgmp-dev
    - libgdal1-dev
    - gdal-bin
    - valgrind

env:
  - ARGS="--resolver lts-1"
  - ARGS="--resolver lts-2"
  - ARGS="--resolver lts-3"
  - ARGS="--resolver nightly"

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.5.0/stack-0.1.5.0-x86_64-linux.tar.gz | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'
- stack $ARGS --no-terminal --install-ghc setup
- stack exec c2hs --version
- gdalinfo --version

script:
- stack $ARGS --no-terminal test --haddock
- find .stack-work -type f -name spec -exec valgrind --leak-check=full {} ';'

cache:
  directories:
  - $HOME/.stack
