sudo: false

language: cpp

addons:
  apt:
    packages:
      - libgmp-dev
      - valgrind
      - libarmadillo-dev
      - libcurl-ssl-dev
      - libcurl4-gnutls-dev
      - libdap-dev
      - libepsilon-dev
      - libexpat1-dev
      - libfreexl-dev
      - libgeos-dev
      - libgif-dev
      - libhdf4-alt-dev
      - libhdf5-dev
      - libjasper-dev
      - libjpeg-dev
      - libkml-dev
      - liblzma-dev
      - libmysqlclient-dev
      - libnetcdf-dev
      - libogdi3.2-dev
      - libopenjpeg-dev
      - libpng-dev
      - libpoppler-private-dev
      - libpq-dev
      - libproj-dev
      - libspatialite-dev
      - libsqlite3-dev
      - liburiparser-dev
      - libwebp-dev
      - libxerces-c-dev
      - libxml2-dev
      - netcdf-bin
      - patch
      - unixodbc-dev
      - zlib1g-dev

env:
  - ARGS="--resolver lts-2"   GDAL="1.10.1"
  - ARGS="--resolver lts-2"   GDAL="1.11.2"
  - ARGS="--resolver lts-2"   GDAL="2.0.1"
  - ARGS="--resolver lts-3"   GDAL="1.10.1"
  - ARGS="--resolver lts-3"   GDAL="1.11.2"
  - ARGS="--resolver lts-3"   GDAL="2.0.1"
  - ARGS="--resolver nightly" GDAL="2.0.1"

before_install:
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'
- stack $ARGS --no-terminal --install-ghc setup
- source .travis-install-gdal.bash_source
- gdal-config --version

script:
- stack $ARGS --no-terminal test --haddock
- find .stack-work -type f -name spec -exec valgrind --leak-check=full {} ';'

before_cache:
  - rm -rf $HOME/.stack/snapshots/*/nightly*
cache:
  apt: true
  directories:
  - $HOME/.stack
  - $HOME/.local
